# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Geo
    module Type
      # A latitude-longitude viewport, represented as two diagonally opposite `low`
      # and `high` points. A viewport is considered a closed region, i.e. it includes
      # its boundary. The latitude bounds must range between -90 to 90 degrees
      # inclusive, and the longitude bounds must range between -180 to 180 degrees
      # inclusive. Various cases include:
      #
      #  - If `low` = `high`, the viewport consists of that single point.
      #
      #  - If `low.longitude` > `high.longitude`, the longitude range is inverted
      #    (the viewport crosses the 180 degree longitude line).
      #
      #  - If `low.longitude` = -180 degrees and `high.longitude` = 180 degrees,
      #    the viewport includes all longitudes.
      #
      #  - If `low.longitude` = 180 degrees and `high.longitude` = -180 degrees,
      #    the longitude range is empty.
      #
      #  - If `low.latitude` > `high.latitude`, the latitude range is empty.
      #
      # Both `low` and `high` must be populated, and the represented box cannot be
      # empty (as specified by the definitions above). An empty viewport will result
      # in an error.
      #
      # For example, this viewport fully encloses New York City:
      #
      # {
      #     "low": {
      #         "latitude": 40.477398,
      #         "longitude": -74.259087
      #     },
      #     "high": {
      #         "latitude": 40.91618,
      #         "longitude": -73.70018
      #     }
      # }
      # @!attribute [rw] low
      #   @return [::Google::Type::LatLng]
      #     Required. The low point of the viewport.
      # @!attribute [rw] high
      #   @return [::Google::Type::LatLng]
      #     Required. The high point of the viewport.
      class Viewport
        include ::Google::Protobuf::MessageExts
        extend ::Google::Protobuf::MessageExts::ClassMethods
      end
    end
  end
end
