# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Type
    # Represents an amount of money with its currency type.
    # @!attribute [rw] currency_code
    #   @return [::String]
    #     The 3-letter currency code defined in ISO 4217.
    # @!attribute [rw] units
    #   @return [::Integer]
    #     The whole units of the amount.
    #     For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
    # @!attribute [rw] nanos
    #   @return [::Integer]
    #     Number of nano (10^-9) units of the amount.
    #     The value must be between -999,999,999 and +999,999,999 inclusive.
    #     If `units` is positive, `nanos` must be positive or zero.
    #     If `units` is zero, `nanos` can be positive, zero, or negative.
    #     If `units` is negative, `nanos` must be negative or zero.
    #     For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
    class Money
      include ::Google::Protobuf::MessageExts
      extend ::Google::Protobuf::MessageExts::ClassMethods
    end
  end
end
