# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # A set of values used to specify the mode of travel.
        # NOTE: `WALK`, `BICYCLE`, and `TWO_WHEELER` routes are in beta and might
        # sometimes be missing clear sidewalks, pedestrian paths, or bicycling paths.
        # You must display this warning to the user for all walking, bicycling, and
        # two-wheel routes that you display in your app.
        module RouteTravelMode
          # No travel mode specified. Defaults to `DRIVE`.
          TRAVEL_MODE_UNSPECIFIED = 0

          # Travel by passenger car.
          DRIVE = 1

          # Travel by bicycle.
          BICYCLE = 2

          # Travel by walking.
          WALK = 3

          # Two-wheeled, motorized vehicle. For example, motorcycle. Note that this
          # differs from the `BICYCLE` travel mode which covers human-powered mode.
          TWO_WHEELER = 4

          # Travel by public transit routes, where available.
          TRANSIT = 7
        end
      end
    end
  end
end
