# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # Contains a route, which consists of a series of connected road segments
        # that join beginning, ending, and intermediate waypoints.
        # @!attribute [rw] route_labels
        #   @return [::Array<::Google::Maps::Routing::V2::RouteLabel>]
        #     Labels for the `Route` that are useful to identify specific properties
        #     of the route to compare against others.
        # @!attribute [rw] legs
        #   @return [::Array<::Google::Maps::Routing::V2::RouteLeg>]
        #     A collection of legs (path segments between waypoints) that make up the
        #     route. Each leg corresponds to the trip between two non-`via`
        #     {::Google::Maps::Routing::V2::Waypoint Waypoints}. For example, a route with no
        #     intermediate waypoints has only one leg. A route that includes one
        #     non-`via` intermediate waypoint has two legs. A route that includes one
        #     `via` intermediate waypoint has one leg. The order of the legs matches the
        #     order of waypoints from `origin` to `intermediates` to `destination`.
        # @!attribute [rw] distance_meters
        #   @return [::Integer]
        #     The travel distance of the route, in meters.
        # @!attribute [rw] duration
        #   @return [::Google::Protobuf::Duration]
        #     The length of time needed to navigate the route. If you set the
        #     `routing_preference` to `TRAFFIC_UNAWARE`, then this value is the same as
        #     `static_duration`. If you set the `routing_preference` to either
        #     `TRAFFIC_AWARE` or `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated
        #     taking traffic conditions into account.
        # @!attribute [rw] static_duration
        #   @return [::Google::Protobuf::Duration]
        #     The duration of travel through the route without taking traffic
        #     conditions into consideration.
        # @!attribute [rw] polyline
        #   @return [::Google::Maps::Routing::V2::Polyline]
        #     The overall route polyline. This polyline is the combined polyline of
        #     all `legs`.
        # @!attribute [rw] description
        #   @return [::String]
        #     A description of the route.
        # @!attribute [rw] warnings
        #   @return [::Array<::String>]
        #     An array of warnings to show when displaying the route.
        # @!attribute [rw] viewport
        #   @return [::Google::Geo::Type::Viewport]
        #     The viewport bounding box of the polyline.
        # @!attribute [rw] travel_advisory
        #   @return [::Google::Maps::Routing::V2::RouteTravelAdvisory]
        #     Additional information about the route.
        # @!attribute [rw] optimized_intermediate_waypoint_index
        #   @return [::Array<::Integer>]
        #     If you set
        #     {::Google::Maps::Routing::V2::ComputeRoutesRequest#optimize_waypoint_order optimize_waypoint_order}
        #     to true, this field contains the optimized ordering of intermediate
        #     waypoints. Otherwise, this field is empty.
        #     For example, if you give an input of Origin: LA; Intermediate waypoints:
        #     Dallas, Bangor, Phoenix; Destination: New York; and the optimized
        #     intermediate waypoint order is Phoenix, Dallas, Bangor, then this field
        #     contains the values [2, 0, 1]. The index starts with 0 for the first
        #     intermediate waypoint provided in the input.
        # @!attribute [rw] localized_values
        #   @return [::Google::Maps::Routing::V2::Route::RouteLocalizedValues]
        #     Text representations of properties of the `Route`.
        # @!attribute [rw] route_token
        #   @return [::String]
        #     A web-safe, base64-encoded route token that can be passed to the Navigation
        #     SDK, that allows the Navigation SDK to reconstruct the route during
        #     navigation, and, in the event of rerouting, honor the original intention
        #     when you created the route by calling ComputeRoutes. Customers should treat
        #     this token as an opaque blob. It is not meant for reading or mutating.
        #     NOTE: `Route.route_token` is only available for requests that have set
        #     `ComputeRoutesRequest.routing_preference` to `TRAFFIC_AWARE` or
        #     `TRAFFIC_AWARE_OPTIMAL`. `Route.route_token` is not supported for requests
        #     that have Via waypoints.
        class Route
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Text representations of certain properties.
          # @!attribute [rw] distance
          #   @return [::Google::Type::LocalizedText]
          #     Travel distance represented in text form.
          # @!attribute [rw] duration
          #   @return [::Google::Type::LocalizedText]
          #     Duration taking traffic conditions into consideration, represented in
          #     text form. Note: If you did not request traffic information, this value
          #     will be the same value as static_duration.
          # @!attribute [rw] static_duration
          #   @return [::Google::Type::LocalizedText]
          #     Duration without taking traffic conditions into
          #     consideration, represented in text form.
          # @!attribute [rw] transit_fare
          #   @return [::Google::Type::LocalizedText]
          #     Transit fare represented in text form.
          class RouteLocalizedValues
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end

        # Contains the additional information that the user should be informed
        # about, such as possible traffic zone restrictions.
        # @!attribute [rw] toll_info
        #   @return [::Google::Maps::Routing::V2::TollInfo]
        #     Contains information about tolls on the route. This field is only populated
        #     if tolls are expected on the route. If this field is set, but the
        #     estimatedPrice subfield is not populated, then the route contains tolls,
        #     but the estimated price is unknown. If this field is not set, then there
        #     are no tolls expected on the route.
        # @!attribute [rw] speed_reading_intervals
        #   @return [::Array<::Google::Maps::Routing::V2::SpeedReadingInterval>]
        #     Speed reading intervals detailing traffic density. Applicable in case of
        #     `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
        #     The intervals cover the entire polyline of the route without overlap.
        #     The start point of a specified interval is the same as the end point of the
        #     preceding interval.
        #
        #     Example:
        #
        #         polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
        #         speed_reading_intervals: [A,C), [C,D), [D,G).
        # @!attribute [rw] fuel_consumption_microliters
        #   @return [::Integer]
        #     The predicted fuel consumption in microliters.
        # @!attribute [rw] route_restrictions_partially_ignored
        #   @return [::Boolean]
        #     Returned route may have restrictions that are not suitable for requested
        #     travel mode or route modifiers.
        # @!attribute [rw] transit_fare
        #   @return [::Google::Type::Money]
        #     If present, contains the total fare or ticket costs on this route
        #     This property is only returned for `TRANSIT` requests and only
        #     for routes where fare information is available for all transit steps.
        class RouteTravelAdvisory
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Contains the additional information that the user should be informed
        # about on a leg step, such as possible traffic zone restrictions.
        # @!attribute [rw] toll_info
        #   @return [::Google::Maps::Routing::V2::TollInfo]
        #     Contains information about tolls on the specific `RouteLeg`.
        #     This field is only populated if we expect there are tolls on the
        #     `RouteLeg`. If this field is set but the estimated_price subfield is not
        #     populated, we expect that road contains tolls but we do not know an
        #     estimated price. If this field does not exist, then there is no toll on the
        #     `RouteLeg`.
        # @!attribute [rw] speed_reading_intervals
        #   @return [::Array<::Google::Maps::Routing::V2::SpeedReadingInterval>]
        #     Speed reading intervals detailing traffic density. Applicable in case of
        #     `TRAFFIC_AWARE` and `TRAFFIC_AWARE_OPTIMAL` routing preferences.
        #     The intervals cover the entire polyline of the `RouteLeg` without overlap.
        #     The start point of a specified interval is the same as the end point of the
        #     preceding interval.
        #
        #     Example:
        #
        #         polyline: A ---- B ---- C ---- D ---- E ---- F ---- G
        #         speed_reading_intervals: [A,C), [C,D), [D,G).
        class RouteLegTravelAdvisory
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Contains the additional information that the user should be informed
        # about, such as possible traffic zone restrictions on a leg step.
        # @!attribute [rw] speed_reading_intervals
        #   @return [::Array<::Google::Maps::Routing::V2::SpeedReadingInterval>]
        #     NOTE: This field is not currently populated.
        class RouteLegStepTravelAdvisory
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Contains a segment between non-`via` waypoints.
        # @!attribute [rw] distance_meters
        #   @return [::Integer]
        #     The travel distance of the route leg, in meters.
        # @!attribute [rw] duration
        #   @return [::Google::Protobuf::Duration]
        #     The length of time needed to navigate the leg. If the `route_preference`
        #     is set to `TRAFFIC_UNAWARE`, then this value is the same as
        #     `static_duration`. If the `route_preference` is either `TRAFFIC_AWARE` or
        #     `TRAFFIC_AWARE_OPTIMAL`, then this value is calculated taking traffic
        #     conditions into account.
        # @!attribute [rw] static_duration
        #   @return [::Google::Protobuf::Duration]
        #     The duration of travel through the leg, calculated without taking
        #     traffic conditions into consideration.
        # @!attribute [rw] polyline
        #   @return [::Google::Maps::Routing::V2::Polyline]
        #     The overall polyline for this leg that includes each `step`'s
        #     polyline.
        # @!attribute [rw] start_location
        #   @return [::Google::Maps::Routing::V2::Location]
        #     The start location of this leg. This location might be different from the
        #     provided `origin`. For example, when the provided `origin` is not near a
        #     road, this is a point on the road.
        # @!attribute [rw] end_location
        #   @return [::Google::Maps::Routing::V2::Location]
        #     The end location of this leg. This location might be different from the
        #     provided `destination`. For example, when the provided `destination` is not
        #     near a road, this is a point on the road.
        # @!attribute [rw] steps
        #   @return [::Array<::Google::Maps::Routing::V2::RouteLegStep>]
        #     An array of steps denoting segments within this leg. Each step represents
        #     one navigation instruction.
        # @!attribute [rw] travel_advisory
        #   @return [::Google::Maps::Routing::V2::RouteLegTravelAdvisory]
        #     Contains the additional information that the user should be informed
        #     about, such as possible traffic zone restrictions, on a route leg.
        # @!attribute [rw] localized_values
        #   @return [::Google::Maps::Routing::V2::RouteLeg::RouteLegLocalizedValues]
        #     Text representations of properties of the `RouteLeg`.
        # @!attribute [rw] steps_overview
        #   @return [::Google::Maps::Routing::V2::RouteLeg::StepsOverview]
        #     Overview information about the steps in this `RouteLeg`. This field is only
        #     populated for TRANSIT routes.
        class RouteLeg
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Text representations of certain properties.
          # @!attribute [rw] distance
          #   @return [::Google::Type::LocalizedText]
          #     Travel distance represented in text form.
          # @!attribute [rw] duration
          #   @return [::Google::Type::LocalizedText]
          #     Duration taking traffic conditions into consideration represented in text
          #     form. Note: If you did not request traffic information, this value will
          #     be the same value as static_duration.
          # @!attribute [rw] static_duration
          #   @return [::Google::Type::LocalizedText]
          #     Duration without taking traffic conditions into
          #     consideration, represented in text form.
          class RouteLegLocalizedValues
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Provides overview information about a list of `RouteLegStep`s.
          # @!attribute [rw] multi_modal_segments
          #   @return [::Array<::Google::Maps::Routing::V2::RouteLeg::StepsOverview::MultiModalSegment>]
          #     Summarized information about different multi-modal segments of
          #     the `RouteLeg.steps`. This field is not populated if the `RouteLeg` does
          #     not contain any multi-modal segments in the steps.
          class StepsOverview
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Provides summarized information about different multi-modal segments of
            # the `RouteLeg.steps`. A multi-modal segment is defined as one or more
            # contiguous `RouteLegStep` that have the same `RouteTravelMode`.
            # This field is not populated if the `RouteLeg` does not contain any
            # multi-modal segments in the steps.
            # @!attribute [rw] step_start_index
            #   @return [::Integer]
            #     The corresponding `RouteLegStep` index that is the start of a
            #     multi-modal segment.
            # @!attribute [rw] step_end_index
            #   @return [::Integer]
            #     The corresponding `RouteLegStep` index that is the end of a
            #     multi-modal segment.
            # @!attribute [rw] navigation_instruction
            #   @return [::Google::Maps::Routing::V2::NavigationInstruction]
            #     NavigationInstruction for the multi-modal segment.
            # @!attribute [rw] travel_mode
            #   @return [::Google::Maps::Routing::V2::RouteTravelMode]
            #     The travel mode of the multi-modal segment.
            class MultiModalSegment
              include ::Google::Protobuf::MessageExts
              extend ::Google::Protobuf::MessageExts::ClassMethods
            end
          end
        end

        # Contains a segment of a {::Google::Maps::Routing::V2::RouteLeg RouteLeg}. A
        # step corresponds to a single navigation instruction. Route legs are made up
        # of steps.
        # @!attribute [rw] distance_meters
        #   @return [::Integer]
        #     The travel distance of this step, in meters. In some circumstances, this
        #     field might not have a value.
        # @!attribute [rw] static_duration
        #   @return [::Google::Protobuf::Duration]
        #     The duration of travel through this step without taking traffic conditions
        #     into consideration. In some circumstances, this field might not have a
        #     value.
        # @!attribute [rw] polyline
        #   @return [::Google::Maps::Routing::V2::Polyline]
        #     The polyline associated with this step.
        # @!attribute [rw] start_location
        #   @return [::Google::Maps::Routing::V2::Location]
        #     The start location of this step.
        # @!attribute [rw] end_location
        #   @return [::Google::Maps::Routing::V2::Location]
        #     The end location of this step.
        # @!attribute [rw] navigation_instruction
        #   @return [::Google::Maps::Routing::V2::NavigationInstruction]
        #     Navigation instructions.
        # @!attribute [rw] travel_advisory
        #   @return [::Google::Maps::Routing::V2::RouteLegStepTravelAdvisory]
        #     Contains the additional information that the user should be informed
        #     about, such as possible traffic zone restrictions, on a leg step.
        # @!attribute [rw] localized_values
        #   @return [::Google::Maps::Routing::V2::RouteLegStep::RouteLegStepLocalizedValues]
        #     Text representations of properties of the `RouteLegStep`.
        # @!attribute [rw] transit_details
        #   @return [::Google::Maps::Routing::V2::RouteLegStepTransitDetails]
        #     Details pertaining to this step if the travel mode is `TRANSIT`.
        # @!attribute [rw] travel_mode
        #   @return [::Google::Maps::Routing::V2::RouteTravelMode]
        #     The travel mode used for this step.
        class RouteLegStep
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Text representations of certain properties.
          # @!attribute [rw] distance
          #   @return [::Google::Type::LocalizedText]
          #     Travel distance represented in text form.
          # @!attribute [rw] static_duration
          #   @return [::Google::Type::LocalizedText]
          #     Duration without taking traffic conditions into
          #     consideration, represented in text form.
          class RouteLegStepLocalizedValues
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end

        # Additional information for the `RouteLegStep` related to `TRANSIT` routes.
        # @!attribute [rw] stop_details
        #   @return [::Google::Maps::Routing::V2::RouteLegStepTransitDetails::TransitStopDetails]
        #     Information about the arrival and departure stops for the step.
        # @!attribute [rw] localized_values
        #   @return [::Google::Maps::Routing::V2::RouteLegStepTransitDetails::TransitDetailsLocalizedValues]
        #     Text representations of properties of the `RouteLegStepTransitDetails`.
        # @!attribute [rw] headsign
        #   @return [::String]
        #     Specifies the direction in which to travel on this line as marked on
        #     the vehicle or at the departure stop. The direction is often the terminus
        #     station.
        # @!attribute [rw] headway
        #   @return [::Google::Protobuf::Duration]
        #     Specifies the expected time as a duration between departures from the same
        #     stop at this time. For example, with a headway seconds value of 600, you
        #     would expect a ten minute wait if you should miss your bus.
        # @!attribute [rw] transit_line
        #   @return [::Google::Maps::Routing::V2::TransitLine]
        #     Information about the transit line used in this step.
        # @!attribute [rw] stop_count
        #   @return [::Integer]
        #     The number of stops from the departure to the arrival stop. This count
        #     includes the arrival stop, but excludes the departure stop. For example, if
        #     your route leaves from Stop A, passes through stops B and C, and arrives at
        #     stop D, stop_count will return 3.
        # @!attribute [rw] trip_short_text
        #   @return [::String]
        #     The text that appears in schedules and sign boards to identify a transit
        #     trip to passengers. The text should uniquely identify a trip within a
        #     service day. For example, "538" is the `trip_short_text` of the Amtrak
        #     train that leaves San Jose, CA at 15:10 on weekdays to Sacramento, CA.
        class RouteLegStepTransitDetails
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # Details about the transit stops for the `RouteLegStep`
          # @!attribute [rw] arrival_stop
          #   @return [::Google::Maps::Routing::V2::TransitStop]
          #     Information about the arrival stop for the step.
          # @!attribute [rw] arrival_time
          #   @return [::Google::Protobuf::Timestamp]
          #     The estimated time of arrival for the step.
          # @!attribute [rw] departure_stop
          #   @return [::Google::Maps::Routing::V2::TransitStop]
          #     Information about the departure stop for the step.
          # @!attribute [rw] departure_time
          #   @return [::Google::Protobuf::Timestamp]
          #     The estimated time of departure for the step.
          class TransitStopDetails
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Localized descriptions of values for RouteTransitDetails.
          # @!attribute [rw] arrival_time
          #   @return [::Google::Maps::Routing::V2::LocalizedTime]
          #     Time in its formatted text representation with a corresponding time zone.
          # @!attribute [rw] departure_time
          #   @return [::Google::Maps::Routing::V2::LocalizedTime]
          #     Time in its formatted text representation with a corresponding time zone.
          class TransitDetailsLocalizedValues
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
