# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # Encapsulates a set of optional conditions to satisfy when calculating the
        # routes.
        # @!attribute [rw] avoid_tolls
        #   @return [::Boolean]
        #     When set to true, avoids toll roads where reasonable, giving preference to
        #     routes not containing toll roads. Applies only to the `DRIVE` and
        #     `TWO_WHEELER` {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        # @!attribute [rw] avoid_highways
        #   @return [::Boolean]
        #     When set to true, avoids highways where reasonable, giving preference to
        #     routes not containing highways. Applies only to the `DRIVE` and
        #     `TWO_WHEELER` {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        # @!attribute [rw] avoid_ferries
        #   @return [::Boolean]
        #     When set to true, avoids ferries where reasonable, giving preference to
        #     routes not containing ferries. Applies only to the `DRIVE` and`TWO_WHEELER`
        #     {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        # @!attribute [rw] avoid_indoor
        #   @return [::Boolean]
        #     When set to true, avoids navigating indoors where reasonable, giving
        #     preference to routes not containing indoor navigation. Applies only to the
        #     `WALK` {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        # @!attribute [rw] vehicle_info
        #   @return [::Google::Maps::Routing::V2::VehicleInfo]
        #     Specifies the vehicle information.
        # @!attribute [rw] toll_passes
        #   @return [::Array<::Google::Maps::Routing::V2::TollPass>]
        #     Encapsulates information about toll passes.
        #     If toll passes are provided, the API tries to return the pass price. If
        #     toll passes are not provided, the API treats the toll pass as unknown and
        #     tries to return the cash price.
        #     Applies only to the `DRIVE` and `TWO_WHEELER`
        #     {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        class RouteModifiers
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end
      end
    end
  end
end
