# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # Labels for the {::Google::Maps::Routing::V2::Route Route} that are useful to
        # identify specific properties of the route to compare against others.
        module RouteLabel
          # Default - not used.
          ROUTE_LABEL_UNSPECIFIED = 0

          # The default "best" route returned for the route computation.
          DEFAULT_ROUTE = 1

          # An alternative to the default "best" route. Routes like this will be
          # returned when
          # {::Google::Maps::Routing::V2::ComputeRoutesRequest#compute_alternative_routes compute_alternative_routes}
          # is specified.
          DEFAULT_ROUTE_ALTERNATE = 2

          # Fuel efficient route. Routes labeled with this value are determined to be
          # optimized for Eco parameters such as fuel consumption.
          FUEL_EFFICIENT = 3
        end
      end
    end
  end
end
