# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # Specifies the assumptions to use when calculating time in traffic. This
        # setting affects the value returned in the `duration` field in the
        # response, which contains the predicted time in traffic based on historical
        # averages.
        module TrafficModel
          # Unused. If specified, will default to `BEST_GUESS`.
          TRAFFIC_MODEL_UNSPECIFIED = 0

          # Indicates that the returned `duration` should be the best
          # estimate of travel time given what is known about both historical traffic
          # conditions and live traffic. Live traffic becomes more important the closer
          # the `departure_time` is to now.
          BEST_GUESS = 1

          # Indicates that the returned duration should be longer than the
          # actual travel time on most days, though occasional days with particularly
          # bad traffic conditions may exceed this value.
          PESSIMISTIC = 2

          # Indicates that the returned duration should be shorter than the actual
          # travel time on most days, though occasional days with particularly good
          # traffic conditions may be faster than this value.
          OPTIMISTIC = 3
        end
      end
    end
  end
end
