# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # A transit agency that operates a transit line.
        # @!attribute [rw] name
        #   @return [::String]
        #     The name of this transit agency.
        # @!attribute [rw] phone_number
        #   @return [::String]
        #     The transit agency's locale-specific formatted phone number.
        # @!attribute [rw] uri
        #   @return [::String]
        #     The transit agency's URI.
        class TransitAgency
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Contains information about the transit line used in this step.
        # @!attribute [rw] agencies
        #   @return [::Array<::Google::Maps::Routing::V2::TransitAgency>]
        #     The transit agency (or agencies) that operates this transit line.
        # @!attribute [rw] name
        #   @return [::String]
        #     The full name of this transit line, For example, "8 Avenue Local".
        # @!attribute [rw] uri
        #   @return [::String]
        #     the URI for this transit line as provided by the transit agency.
        # @!attribute [rw] color
        #   @return [::String]
        #     The color commonly used in signage for this line. Represented in
        #     hexadecimal.
        # @!attribute [rw] icon_uri
        #   @return [::String]
        #     The URI for the icon associated with this line.
        # @!attribute [rw] name_short
        #   @return [::String]
        #     The short name of this transit line. This name will normally be a line
        #     number, such as "M7" or "355".
        # @!attribute [rw] text_color
        #   @return [::String]
        #     The color commonly used in text on signage for this line. Represented in
        #     hexadecimal.
        # @!attribute [rw] vehicle
        #   @return [::Google::Maps::Routing::V2::TransitVehicle]
        #     The type of vehicle that operates on this transit line.
        class TransitLine
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Information about a transit stop.
        # @!attribute [rw] name
        #   @return [::String]
        #     The name of the transit stop.
        # @!attribute [rw] location
        #   @return [::Google::Maps::Routing::V2::Location]
        #     The location of the stop expressed in latitude/longitude coordinates.
        class TransitStop
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Information about a vehicle used in transit routes.
        # @!attribute [rw] name
        #   @return [::Google::Type::LocalizedText]
        #     The name of this vehicle, capitalized.
        # @!attribute [rw] type
        #   @return [::Google::Maps::Routing::V2::TransitVehicle::TransitVehicleType]
        #     The type of vehicle used.
        # @!attribute [rw] icon_uri
        #   @return [::String]
        #     The URI for an icon associated with this vehicle type.
        # @!attribute [rw] local_icon_uri
        #   @return [::String]
        #     The URI for the icon associated with this vehicle type, based on the local
        #     transport signage.
        class TransitVehicle
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # The type of vehicles for transit routes.
          module TransitVehicleType
            # Unused.
            TRANSIT_VEHICLE_TYPE_UNSPECIFIED = 0

            # Bus.
            BUS = 1

            # A vehicle that operates on a cable, usually on the ground. Aerial cable
            # cars may be of the type `GONDOLA_LIFT`.
            CABLE_CAR = 2

            # Commuter rail.
            COMMUTER_TRAIN = 3

            # Ferry.
            FERRY = 4

            # A vehicle that is pulled up a steep incline by a cable. A Funicular
            # typically consists of two cars, with each car acting as a counterweight
            # for the other.
            FUNICULAR = 5

            # An aerial cable car.
            GONDOLA_LIFT = 6

            # Heavy rail.
            HEAVY_RAIL = 7

            # High speed train.
            HIGH_SPEED_TRAIN = 8

            # Intercity bus.
            INTERCITY_BUS = 9

            # Long distance train.
            LONG_DISTANCE_TRAIN = 10

            # Light rail transit.
            METRO_RAIL = 11

            # Monorail.
            MONORAIL = 12

            # All other vehicles.
            OTHER = 13

            # Rail.
            RAIL = 14

            # Share taxi is a kind of bus with the ability to drop off and pick up
            # passengers anywhere on its route.
            SHARE_TAXI = 15

            # Underground light rail.
            SUBWAY = 16

            # Above ground light rail.
            TRAM = 17

            # Trolleybus.
            TROLLEYBUS = 18
          end
        end
      end
    end
  end
end
