# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # Preferences for `TRANSIT` based routes that influence the route that is
        # returned.
        # @!attribute [rw] allowed_travel_modes
        #   @return [::Array<::Google::Maps::Routing::V2::TransitPreferences::TransitTravelMode>]
        #     A set of travel modes to use when getting a `TRANSIT` route. Defaults to
        #     all supported modes of travel.
        # @!attribute [rw] routing_preference
        #   @return [::Google::Maps::Routing::V2::TransitPreferences::TransitRoutingPreference]
        #     A routing preference that, when specified, influences the `TRANSIT` route
        #     returned.
        class TransitPreferences
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # A set of values used to specify the mode of transit.
          module TransitTravelMode
            # No transit travel mode specified.
            TRANSIT_TRAVEL_MODE_UNSPECIFIED = 0

            # Travel by bus.
            BUS = 1

            # Travel by subway.
            SUBWAY = 2

            # Travel by train.
            TRAIN = 3

            # Travel by light rail or tram.
            LIGHT_RAIL = 4

            # Travel by rail. This is equivalent to a combination of `SUBWAY`, `TRAIN`,
            # and `LIGHT_RAIL`.
            RAIL = 5
          end

          # Specifies routing preferences for transit routes.
          module TransitRoutingPreference
            # No preference specified.
            TRANSIT_ROUTING_PREFERENCE_UNSPECIFIED = 0

            # Indicates that the calculated route should prefer limited amounts of
            # walking.
            LESS_WALKING = 1

            # Indicates that the calculated route should prefer a limited number of
            # transfers.
            FEWER_TRANSFERS = 2
          end
        end
      end
    end
  end
end
