# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Maps
    module Routing
      module V2
        # A set of values describing the vehicle's emission type.
        # Applies only to the `DRIVE`
        # {::Google::Maps::Routing::V2::RouteTravelMode RouteTravelMode}.
        module VehicleEmissionType
          # No emission type specified. Default to `GASOLINE`.
          VEHICLE_EMISSION_TYPE_UNSPECIFIED = 0

          # Gasoline/petrol fueled vehicle.
          GASOLINE = 1

          # Electricity powered vehicle.
          ELECTRIC = 2

          # Hybrid fuel (such as gasoline + electric) vehicle.
          HYBRID = 3

          # Diesel fueled vehicle.
          DIESEL = 4
        end
      end
    end
  end
end
