# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/fallback_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/fallback_info.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.FallbackInfo" do
      optional :routing_mode, :enum, 1, "google.maps.routing.v2.FallbackRoutingMode"
      optional :reason, :enum, 2, "google.maps.routing.v2.FallbackReason"
    end
    add_enum "google.maps.routing.v2.FallbackReason" do
      value :FALLBACK_REASON_UNSPECIFIED, 0
      value :SERVER_ERROR, 1
      value :LATENCY_EXCEEDED, 2
    end
    add_enum "google.maps.routing.v2.FallbackRoutingMode" do
      value :FALLBACK_ROUTING_MODE_UNSPECIFIED, 0
      value :FALLBACK_TRAFFIC_UNAWARE, 1
      value :FALLBACK_TRAFFIC_AWARE, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        FallbackInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.FallbackInfo").msgclass
        FallbackReason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.FallbackReason").enummodule
        FallbackRoutingMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.FallbackRoutingMode").enummodule
      end
    end
  end
end
