# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/location.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'google/type/latlng_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/location.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.Location" do
      optional :lat_lng, :message, 1, "google.type.LatLng"
      optional :heading, :message, 2, "google.protobuf.Int32Value"
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Location").msgclass
      end
    end
  end
end
