# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/localized_time.proto

require 'google/protobuf'

require 'google/type/localized_text_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/localized_time.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.LocalizedTime" do
      optional :time, :message, 1, "google.type.LocalizedText"
      optional :time_zone, :string, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        LocalizedTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.LocalizedTime").msgclass
      end
    end
  end
end
