# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/maneuver.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/maneuver.proto", :syntax => :proto3) do
    add_enum "google.maps.routing.v2.Maneuver" do
      value :MANEUVER_UNSPECIFIED, 0
      value :TURN_SLIGHT_LEFT, 1
      value :TURN_SHARP_LEFT, 2
      value :UTURN_LEFT, 3
      value :TURN_LEFT, 4
      value :TURN_SLIGHT_RIGHT, 5
      value :TURN_SHARP_RIGHT, 6
      value :UTURN_RIGHT, 7
      value :TURN_RIGHT, 8
      value :STRAIGHT, 9
      value :RAMP_LEFT, 10
      value :RAMP_RIGHT, 11
      value :MERGE, 12
      value :FORK_LEFT, 13
      value :FORK_RIGHT, 14
      value :FERRY, 15
      value :FERRY_TRAIN, 16
      value :ROUNDABOUT_LEFT, 17
      value :ROUNDABOUT_RIGHT, 18
      value :DEPART, 19
      value :NAME_CHANGE, 20
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        Maneuver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Maneuver").enummodule
      end
    end
  end
end
