# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/navigation_instruction.proto

require 'google/protobuf'

require 'google/maps/routing/v2/maneuver_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/navigation_instruction.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.NavigationInstruction" do
      optional :maneuver, :enum, 1, "google.maps.routing.v2.Maneuver"
      optional :instructions, :string, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        NavigationInstruction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.NavigationInstruction").msgclass
      end
    end
  end
end
