# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/polyline.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/polyline.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.Polyline" do
      oneof :polyline_type do
        optional :encoded_polyline, :string, 1
        optional :geo_json_linestring, :message, 2, "google.protobuf.Struct"
      end
    end
    add_enum "google.maps.routing.v2.PolylineQuality" do
      value :POLYLINE_QUALITY_UNSPECIFIED, 0
      value :HIGH_QUALITY, 1
      value :OVERVIEW, 2
    end
    add_enum "google.maps.routing.v2.PolylineEncoding" do
      value :POLYLINE_ENCODING_UNSPECIFIED, 0
      value :ENCODED_POLYLINE, 1
      value :GEO_JSON_LINESTRING, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        Polyline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Polyline").msgclass
        PolylineQuality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.PolylineQuality").enummodule
        PolylineEncoding = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.PolylineEncoding").enummodule
      end
    end
  end
end
