# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/route_label.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/route_label.proto", :syntax => :proto3) do
    add_enum "google.maps.routing.v2.RouteLabel" do
      value :ROUTE_LABEL_UNSPECIFIED, 0
      value :DEFAULT_ROUTE, 1
      value :DEFAULT_ROUTE_ALTERNATE, 2
      value :FUEL_EFFICIENT, 3
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        RouteLabel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLabel").enummodule
      end
    end
  end
end
