# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/routes_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/api/client_pb'
require 'google/api/field_behavior_pb'
require 'google/maps/routing/v2/fallback_info_pb'
require 'google/maps/routing/v2/geocoding_results_pb'
require 'google/maps/routing/v2/polyline_pb'
require 'google/maps/routing/v2/route_pb'
require 'google/maps/routing/v2/route_modifiers_pb'
require 'google/maps/routing/v2/route_travel_mode_pb'
require 'google/maps/routing/v2/routing_preference_pb'
require 'google/maps/routing/v2/traffic_model_pb'
require 'google/maps/routing/v2/transit_preferences_pb'
require 'google/maps/routing/v2/units_pb'
require 'google/maps/routing/v2/waypoint_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'google/rpc/status_pb'
require 'google/type/localized_text_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/routes_service.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.ComputeRoutesRequest" do
      optional :origin, :message, 1, "google.maps.routing.v2.Waypoint"
      optional :destination, :message, 2, "google.maps.routing.v2.Waypoint"
      repeated :intermediates, :message, 3, "google.maps.routing.v2.Waypoint"
      optional :travel_mode, :enum, 4, "google.maps.routing.v2.RouteTravelMode"
      optional :routing_preference, :enum, 5, "google.maps.routing.v2.RoutingPreference"
      optional :polyline_quality, :enum, 6, "google.maps.routing.v2.PolylineQuality"
      optional :polyline_encoding, :enum, 12, "google.maps.routing.v2.PolylineEncoding"
      optional :departure_time, :message, 7, "google.protobuf.Timestamp"
      optional :arrival_time, :message, 19, "google.protobuf.Timestamp"
      optional :compute_alternative_routes, :bool, 8
      optional :route_modifiers, :message, 9, "google.maps.routing.v2.RouteModifiers"
      optional :language_code, :string, 10
      optional :region_code, :string, 16
      optional :units, :enum, 11, "google.maps.routing.v2.Units"
      optional :optimize_waypoint_order, :bool, 13
      repeated :requested_reference_routes, :enum, 14, "google.maps.routing.v2.ComputeRoutesRequest.ReferenceRoute"
      repeated :extra_computations, :enum, 15, "google.maps.routing.v2.ComputeRoutesRequest.ExtraComputation"
      optional :traffic_model, :enum, 18, "google.maps.routing.v2.TrafficModel"
      optional :transit_preferences, :message, 20, "google.maps.routing.v2.TransitPreferences"
    end
    add_enum "google.maps.routing.v2.ComputeRoutesRequest.ReferenceRoute" do
      value :REFERENCE_ROUTE_UNSPECIFIED, 0
      value :FUEL_EFFICIENT, 1
    end
    add_enum "google.maps.routing.v2.ComputeRoutesRequest.ExtraComputation" do
      value :EXTRA_COMPUTATION_UNSPECIFIED, 0
      value :TOLLS, 1
      value :FUEL_CONSUMPTION, 2
      value :TRAFFIC_ON_POLYLINE, 3
      value :HTML_FORMATTED_NAVIGATION_INSTRUCTIONS, 4
    end
    add_message "google.maps.routing.v2.ComputeRoutesResponse" do
      repeated :routes, :message, 1, "google.maps.routing.v2.Route"
      optional :fallback_info, :message, 2, "google.maps.routing.v2.FallbackInfo"
      optional :geocoding_results, :message, 3, "google.maps.routing.v2.GeocodingResults"
    end
    add_message "google.maps.routing.v2.ComputeRouteMatrixRequest" do
      repeated :origins, :message, 1, "google.maps.routing.v2.RouteMatrixOrigin"
      repeated :destinations, :message, 2, "google.maps.routing.v2.RouteMatrixDestination"
      optional :travel_mode, :enum, 3, "google.maps.routing.v2.RouteTravelMode"
      optional :routing_preference, :enum, 4, "google.maps.routing.v2.RoutingPreference"
      optional :departure_time, :message, 5, "google.protobuf.Timestamp"
      optional :arrival_time, :message, 11, "google.protobuf.Timestamp"
      optional :language_code, :string, 6
      optional :region_code, :string, 9
      repeated :extra_computations, :enum, 8, "google.maps.routing.v2.ComputeRouteMatrixRequest.ExtraComputation"
      optional :traffic_model, :enum, 10, "google.maps.routing.v2.TrafficModel"
      optional :transit_preferences, :message, 12, "google.maps.routing.v2.TransitPreferences"
    end
    add_enum "google.maps.routing.v2.ComputeRouteMatrixRequest.ExtraComputation" do
      value :EXTRA_COMPUTATION_UNSPECIFIED, 0
      value :TOLLS, 1
    end
    add_message "google.maps.routing.v2.RouteMatrixOrigin" do
      optional :waypoint, :message, 1, "google.maps.routing.v2.Waypoint"
      optional :route_modifiers, :message, 2, "google.maps.routing.v2.RouteModifiers"
    end
    add_message "google.maps.routing.v2.RouteMatrixDestination" do
      optional :waypoint, :message, 1, "google.maps.routing.v2.Waypoint"
    end
    add_message "google.maps.routing.v2.RouteMatrixElement" do
      proto3_optional :origin_index, :int32, 1
      proto3_optional :destination_index, :int32, 2
      optional :status, :message, 3, "google.rpc.Status"
      optional :condition, :enum, 9, "google.maps.routing.v2.RouteMatrixElementCondition"
      optional :distance_meters, :int32, 4
      optional :duration, :message, 5, "google.protobuf.Duration"
      optional :static_duration, :message, 6, "google.protobuf.Duration"
      optional :travel_advisory, :message, 7, "google.maps.routing.v2.RouteTravelAdvisory"
      optional :fallback_info, :message, 8, "google.maps.routing.v2.FallbackInfo"
      optional :localized_values, :message, 10, "google.maps.routing.v2.RouteMatrixElement.LocalizedValues"
    end
    add_message "google.maps.routing.v2.RouteMatrixElement.LocalizedValues" do
      optional :distance, :message, 1, "google.type.LocalizedText"
      optional :duration, :message, 2, "google.type.LocalizedText"
      optional :static_duration, :message, 3, "google.type.LocalizedText"
      optional :transit_fare, :message, 4, "google.type.LocalizedText"
    end
    add_enum "google.maps.routing.v2.RouteMatrixElementCondition" do
      value :ROUTE_MATRIX_ELEMENT_CONDITION_UNSPECIFIED, 0
      value :ROUTE_EXISTS, 1
      value :ROUTE_NOT_FOUND, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        ComputeRoutesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRoutesRequest").msgclass
        ComputeRoutesRequest::ReferenceRoute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRoutesRequest.ReferenceRoute").enummodule
        ComputeRoutesRequest::ExtraComputation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRoutesRequest.ExtraComputation").enummodule
        ComputeRoutesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRoutesResponse").msgclass
        ComputeRouteMatrixRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRouteMatrixRequest").msgclass
        ComputeRouteMatrixRequest::ExtraComputation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.ComputeRouteMatrixRequest.ExtraComputation").enummodule
        RouteMatrixOrigin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteMatrixOrigin").msgclass
        RouteMatrixDestination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteMatrixDestination").msgclass
        RouteMatrixElement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteMatrixElement").msgclass
        RouteMatrixElement::LocalizedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteMatrixElement.LocalizedValues").msgclass
        RouteMatrixElementCondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteMatrixElementCondition").enummodule
      end
    end
  end
end
