# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/routing_preference.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/routing_preference.proto", :syntax => :proto3) do
    add_enum "google.maps.routing.v2.RoutingPreference" do
      value :ROUTING_PREFERENCE_UNSPECIFIED, 0
      value :TRAFFIC_UNAWARE, 1
      value :TRAFFIC_AWARE, 2
      value :TRAFFIC_AWARE_OPTIMAL, 3
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        RoutingPreference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RoutingPreference").enummodule
      end
    end
  end
end
