# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/route.proto

require 'google/protobuf'

require 'google/geo/type/viewport_pb'
require 'google/maps/routing/v2/localized_time_pb'
require 'google/maps/routing/v2/location_pb'
require 'google/maps/routing/v2/navigation_instruction_pb'
require 'google/maps/routing/v2/polyline_pb'
require 'google/maps/routing/v2/route_label_pb'
require 'google/maps/routing/v2/route_travel_mode_pb'
require 'google/maps/routing/v2/speed_reading_interval_pb'
require 'google/maps/routing/v2/toll_info_pb'
require 'google/maps/routing/v2/transit_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'google/type/localized_text_pb'
require 'google/type/money_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/route.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.Route" do
      repeated :route_labels, :enum, 13, "google.maps.routing.v2.RouteLabel"
      repeated :legs, :message, 1, "google.maps.routing.v2.RouteLeg"
      optional :distance_meters, :int32, 2
      optional :duration, :message, 3, "google.protobuf.Duration"
      optional :static_duration, :message, 4, "google.protobuf.Duration"
      optional :polyline, :message, 5, "google.maps.routing.v2.Polyline"
      optional :description, :string, 6
      repeated :warnings, :string, 7
      optional :viewport, :message, 8, "google.geo.type.Viewport"
      optional :travel_advisory, :message, 9, "google.maps.routing.v2.RouteTravelAdvisory"
      repeated :optimized_intermediate_waypoint_index, :int32, 10
      optional :localized_values, :message, 11, "google.maps.routing.v2.Route.RouteLocalizedValues"
      optional :route_token, :string, 12
    end
    add_message "google.maps.routing.v2.Route.RouteLocalizedValues" do
      optional :distance, :message, 1, "google.type.LocalizedText"
      optional :duration, :message, 2, "google.type.LocalizedText"
      optional :static_duration, :message, 3, "google.type.LocalizedText"
      optional :transit_fare, :message, 4, "google.type.LocalizedText"
    end
    add_message "google.maps.routing.v2.RouteTravelAdvisory" do
      optional :toll_info, :message, 2, "google.maps.routing.v2.TollInfo"
      repeated :speed_reading_intervals, :message, 3, "google.maps.routing.v2.SpeedReadingInterval"
      optional :fuel_consumption_microliters, :int64, 5
      optional :route_restrictions_partially_ignored, :bool, 6
      optional :transit_fare, :message, 7, "google.type.Money"
    end
    add_message "google.maps.routing.v2.RouteLegTravelAdvisory" do
      optional :toll_info, :message, 1, "google.maps.routing.v2.TollInfo"
      repeated :speed_reading_intervals, :message, 2, "google.maps.routing.v2.SpeedReadingInterval"
    end
    add_message "google.maps.routing.v2.RouteLegStepTravelAdvisory" do
      repeated :speed_reading_intervals, :message, 1, "google.maps.routing.v2.SpeedReadingInterval"
    end
    add_message "google.maps.routing.v2.RouteLeg" do
      optional :distance_meters, :int32, 1
      optional :duration, :message, 2, "google.protobuf.Duration"
      optional :static_duration, :message, 3, "google.protobuf.Duration"
      optional :polyline, :message, 4, "google.maps.routing.v2.Polyline"
      optional :start_location, :message, 5, "google.maps.routing.v2.Location"
      optional :end_location, :message, 6, "google.maps.routing.v2.Location"
      repeated :steps, :message, 7, "google.maps.routing.v2.RouteLegStep"
      optional :travel_advisory, :message, 8, "google.maps.routing.v2.RouteLegTravelAdvisory"
      optional :localized_values, :message, 9, "google.maps.routing.v2.RouteLeg.RouteLegLocalizedValues"
      optional :steps_overview, :message, 10, "google.maps.routing.v2.RouteLeg.StepsOverview"
    end
    add_message "google.maps.routing.v2.RouteLeg.RouteLegLocalizedValues" do
      optional :distance, :message, 1, "google.type.LocalizedText"
      optional :duration, :message, 2, "google.type.LocalizedText"
      optional :static_duration, :message, 3, "google.type.LocalizedText"
    end
    add_message "google.maps.routing.v2.RouteLeg.StepsOverview" do
      repeated :multi_modal_segments, :message, 1, "google.maps.routing.v2.RouteLeg.StepsOverview.MultiModalSegment"
    end
    add_message "google.maps.routing.v2.RouteLeg.StepsOverview.MultiModalSegment" do
      proto3_optional :step_start_index, :int32, 1
      proto3_optional :step_end_index, :int32, 2
      optional :navigation_instruction, :message, 3, "google.maps.routing.v2.NavigationInstruction"
      optional :travel_mode, :enum, 4, "google.maps.routing.v2.RouteTravelMode"
    end
    add_message "google.maps.routing.v2.RouteLegStep" do
      optional :distance_meters, :int32, 1
      optional :static_duration, :message, 2, "google.protobuf.Duration"
      optional :polyline, :message, 3, "google.maps.routing.v2.Polyline"
      optional :start_location, :message, 4, "google.maps.routing.v2.Location"
      optional :end_location, :message, 5, "google.maps.routing.v2.Location"
      optional :navigation_instruction, :message, 6, "google.maps.routing.v2.NavigationInstruction"
      optional :travel_advisory, :message, 7, "google.maps.routing.v2.RouteLegStepTravelAdvisory"
      optional :localized_values, :message, 8, "google.maps.routing.v2.RouteLegStep.RouteLegStepLocalizedValues"
      optional :transit_details, :message, 9, "google.maps.routing.v2.RouteLegStepTransitDetails"
      optional :travel_mode, :enum, 10, "google.maps.routing.v2.RouteTravelMode"
    end
    add_message "google.maps.routing.v2.RouteLegStep.RouteLegStepLocalizedValues" do
      optional :distance, :message, 1, "google.type.LocalizedText"
      optional :static_duration, :message, 3, "google.type.LocalizedText"
    end
    add_message "google.maps.routing.v2.RouteLegStepTransitDetails" do
      optional :stop_details, :message, 1, "google.maps.routing.v2.RouteLegStepTransitDetails.TransitStopDetails"
      optional :localized_values, :message, 2, "google.maps.routing.v2.RouteLegStepTransitDetails.TransitDetailsLocalizedValues"
      optional :headsign, :string, 3
      optional :headway, :message, 4, "google.protobuf.Duration"
      optional :transit_line, :message, 5, "google.maps.routing.v2.TransitLine"
      optional :stop_count, :int32, 6
      optional :trip_short_text, :string, 7
    end
    add_message "google.maps.routing.v2.RouteLegStepTransitDetails.TransitStopDetails" do
      optional :arrival_stop, :message, 1, "google.maps.routing.v2.TransitStop"
      optional :arrival_time, :message, 2, "google.protobuf.Timestamp"
      optional :departure_stop, :message, 3, "google.maps.routing.v2.TransitStop"
      optional :departure_time, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "google.maps.routing.v2.RouteLegStepTransitDetails.TransitDetailsLocalizedValues" do
      optional :arrival_time, :message, 1, "google.maps.routing.v2.LocalizedTime"
      optional :departure_time, :message, 2, "google.maps.routing.v2.LocalizedTime"
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        Route = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Route").msgclass
        Route::RouteLocalizedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Route.RouteLocalizedValues").msgclass
        RouteTravelAdvisory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteTravelAdvisory").msgclass
        RouteLegTravelAdvisory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegTravelAdvisory").msgclass
        RouteLegStepTravelAdvisory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStepTravelAdvisory").msgclass
        RouteLeg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLeg").msgclass
        RouteLeg::RouteLegLocalizedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLeg.RouteLegLocalizedValues").msgclass
        RouteLeg::StepsOverview = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLeg.StepsOverview").msgclass
        RouteLeg::StepsOverview::MultiModalSegment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLeg.StepsOverview.MultiModalSegment").msgclass
        RouteLegStep = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStep").msgclass
        RouteLegStep::RouteLegStepLocalizedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStep.RouteLegStepLocalizedValues").msgclass
        RouteLegStepTransitDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStepTransitDetails").msgclass
        RouteLegStepTransitDetails::TransitStopDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStepTransitDetails.TransitStopDetails").msgclass
        RouteLegStepTransitDetails::TransitDetailsLocalizedValues = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.RouteLegStepTransitDetails.TransitDetailsLocalizedValues").msgclass
      end
    end
  end
end
