# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/toll_passes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/toll_passes.proto", :syntax => :proto3) do
    add_enum "google.maps.routing.v2.TollPass" do
      value :TOLL_PASS_UNSPECIFIED, 0
      value :AU_ETOLL_TAG, 82
      value :AU_EWAY_TAG, 83
      value :AU_LINKT, 2
      value :AR_TELEPASE, 3
      value :BR_AUTO_EXPRESO, 81
      value :BR_CONECTCAR, 7
      value :BR_MOVE_MAIS, 8
      value :BR_PASSA_RAPIDO, 88
      value :BR_SEM_PARAR, 9
      value :BR_TAGGY, 10
      value :BR_VELOE, 11
      value :CA_US_AKWASASNE_SEAWAY_CORPORATE_CARD, 84
      value :CA_US_AKWASASNE_SEAWAY_TRANSIT_CARD, 85
      value :CA_US_BLUE_WATER_EDGE_PASS, 18
      value :CA_US_CONNEXION, 19
      value :CA_US_NEXUS_CARD, 20
      value :ID_E_TOLL, 16
      value :IN_FASTAG, 78
      value :IN_LOCAL_HP_PLATE_EXEMPT, 79
      value :MX_IAVE, 90
      value :MX_PASE, 91
      value :MX_QUICKPASS, 93
      value :MX_SISTEMA_TELEPEAJE_CHIHUAHUA, 89
      value :MX_TAG_IAVE, 12
      value :MX_TAG_TELEVIA, 13
      value :MX_TELEVIA, 92
      value :MX_VIAPASS, 14
      value :US_AL_FREEDOM_PASS, 21
      value :US_AK_ANTON_ANDERSON_TUNNEL_BOOK_OF_10_TICKETS, 22
      value :US_CA_FASTRAK, 4
      value :US_CA_FASTRAK_CAV_STICKER, 86
      value :US_CO_EXPRESSTOLL, 23
      value :US_CO_GO_PASS, 24
      value :US_DE_EZPASSDE, 25
      value :US_FL_BOB_SIKES_TOLL_BRIDGE_PASS, 65
      value :US_FL_DUNES_COMMUNITY_DEVELOPMENT_DISTRICT_EXPRESSCARD, 66
      value :US_FL_EPASS, 67
      value :US_FL_GIBA_TOLL_PASS, 68
      value :US_FL_LEEWAY, 69
      value :US_FL_SUNPASS, 70
      value :US_FL_SUNPASS_PRO, 71
      value :US_IL_EZPASSIL, 73
      value :US_IL_IPASS, 72
      value :US_IN_EZPASSIN, 26
      value :US_KS_BESTPASS_HORIZON, 27
      value :US_KS_KTAG, 28
      value :US_KS_NATIONALPASS, 29
      value :US_KS_PREPASS_ELITEPASS, 30
      value :US_KY_RIVERLINK, 31
      value :US_LA_GEAUXPASS, 32
      value :US_LA_TOLL_TAG, 33
      value :US_MA_EZPASSMA, 6
      value :US_MD_EZPASSMD, 34
      value :US_ME_EZPASSME, 35
      value :US_MI_AMBASSADOR_BRIDGE_PREMIER_COMMUTER_CARD, 36
      value :US_MI_BCPASS, 94
      value :US_MI_GROSSE_ILE_TOLL_BRIDGE_PASS_TAG, 37
      value :US_MI_IQ_PROX_CARD, 38
      value :US_MI_IQ_TAG, 95
      value :US_MI_MACKINAC_BRIDGE_MAC_PASS, 39
      value :US_MI_NEXPRESS_TOLL, 40
      value :US_MN_EZPASSMN, 41
      value :US_NC_EZPASSNC, 42
      value :US_NC_PEACH_PASS, 87
      value :US_NC_QUICK_PASS, 43
      value :US_NH_EZPASSNH, 80
      value :US_NJ_DOWNBEACH_EXPRESS_PASS, 75
      value :US_NJ_EZPASSNJ, 74
      value :US_NY_EXPRESSPASS, 76
      value :US_NY_EZPASSNY, 77
      value :US_OH_EZPASSOH, 44
      value :US_PA_EZPASSPA, 45
      value :US_RI_EZPASSRI, 46
      value :US_SC_PALPASS, 47
      value :US_TX_AVI_TAG, 97
      value :US_TX_BANCPASS, 48
      value :US_TX_DEL_RIO_PASS, 49
      value :US_TX_EFAST_PASS, 50
      value :US_TX_EAGLE_PASS_EXPRESS_CARD, 51
      value :US_TX_EPTOLL, 52
      value :US_TX_EZ_CROSS, 53
      value :US_TX_EZTAG, 54
      value :US_TX_FUEGO_TAG, 96
      value :US_TX_LAREDO_TRADE_TAG, 55
      value :US_TX_PLUSPASS, 56
      value :US_TX_TOLLTAG, 57
      value :US_TX_TXTAG, 58
      value :US_TX_XPRESS_CARD, 59
      value :US_UT_ADAMS_AVE_PARKWAY_EXPRESSCARD, 60
      value :US_VA_EZPASSVA, 61
      value :US_WA_BREEZEBY, 17
      value :US_WA_GOOD_TO_GO, 1
      value :US_WV_EZPASSWV, 62
      value :US_WV_MEMORIAL_BRIDGE_TICKETS, 63
      value :US_WV_NEWELL_TOLL_BRIDGE_TICKET, 64
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        TollPass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TollPass").enummodule
      end
    end
  end
end
