# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/traffic_model.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/traffic_model.proto", :syntax => :proto3) do
    add_enum "google.maps.routing.v2.TrafficModel" do
      value :TRAFFIC_MODEL_UNSPECIFIED, 0
      value :BEST_GUESS, 1
      value :PESSIMISTIC, 2
      value :OPTIMISTIC, 3
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        TrafficModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TrafficModel").enummodule
      end
    end
  end
end
