# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/transit_preferences.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/transit_preferences.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.TransitPreferences" do
      repeated :allowed_travel_modes, :enum, 1, "google.maps.routing.v2.TransitPreferences.TransitTravelMode"
      optional :routing_preference, :enum, 2, "google.maps.routing.v2.TransitPreferences.TransitRoutingPreference"
    end
    add_enum "google.maps.routing.v2.TransitPreferences.TransitTravelMode" do
      value :TRANSIT_TRAVEL_MODE_UNSPECIFIED, 0
      value :BUS, 1
      value :SUBWAY, 2
      value :TRAIN, 3
      value :LIGHT_RAIL, 4
      value :RAIL, 5
    end
    add_enum "google.maps.routing.v2.TransitPreferences.TransitRoutingPreference" do
      value :TRANSIT_ROUTING_PREFERENCE_UNSPECIFIED, 0
      value :LESS_WALKING, 1
      value :FEWER_TRANSFERS, 2
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        TransitPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitPreferences").msgclass
        TransitPreferences::TransitTravelMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitPreferences.TransitTravelMode").enummodule
        TransitPreferences::TransitRoutingPreference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitPreferences.TransitRoutingPreference").enummodule
      end
    end
  end
end
