# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/transit.proto

require 'google/protobuf'

require 'google/maps/routing/v2/location_pb'
require 'google/type/localized_text_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/transit.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.TransitAgency" do
      optional :name, :string, 1
      optional :phone_number, :string, 2
      optional :uri, :string, 3
    end
    add_message "google.maps.routing.v2.TransitLine" do
      repeated :agencies, :message, 1, "google.maps.routing.v2.TransitAgency"
      optional :name, :string, 2
      optional :uri, :string, 3
      optional :color, :string, 4
      optional :icon_uri, :string, 5
      optional :name_short, :string, 6
      optional :text_color, :string, 7
      optional :vehicle, :message, 8, "google.maps.routing.v2.TransitVehicle"
    end
    add_message "google.maps.routing.v2.TransitStop" do
      optional :name, :string, 1
      optional :location, :message, 2, "google.maps.routing.v2.Location"
    end
    add_message "google.maps.routing.v2.TransitVehicle" do
      optional :name, :message, 1, "google.type.LocalizedText"
      optional :type, :enum, 2, "google.maps.routing.v2.TransitVehicle.TransitVehicleType"
      optional :icon_uri, :string, 3
      optional :local_icon_uri, :string, 4
    end
    add_enum "google.maps.routing.v2.TransitVehicle.TransitVehicleType" do
      value :TRANSIT_VEHICLE_TYPE_UNSPECIFIED, 0
      value :BUS, 1
      value :CABLE_CAR, 2
      value :COMMUTER_TRAIN, 3
      value :FERRY, 4
      value :FUNICULAR, 5
      value :GONDOLA_LIFT, 6
      value :HEAVY_RAIL, 7
      value :HIGH_SPEED_TRAIN, 8
      value :INTERCITY_BUS, 9
      value :LONG_DISTANCE_TRAIN, 10
      value :METRO_RAIL, 11
      value :MONORAIL, 12
      value :OTHER, 13
      value :RAIL, 14
      value :SHARE_TAXI, 15
      value :SUBWAY, 16
      value :TRAM, 17
      value :TROLLEYBUS, 18
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        TransitAgency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitAgency").msgclass
        TransitLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitLine").msgclass
        TransitStop = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitStop").msgclass
        TransitVehicle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitVehicle").msgclass
        TransitVehicle::TransitVehicleType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.TransitVehicle.TransitVehicleType").enummodule
      end
    end
  end
end
