# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/vehicle_info.proto

require 'google/protobuf'

require 'google/maps/routing/v2/vehicle_emission_type_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/vehicle_info.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.VehicleInfo" do
      optional :emission_type, :enum, 2, "google.maps.routing.v2.VehicleEmissionType"
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        VehicleInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.VehicleInfo").msgclass
      end
    end
  end
end
