# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/maps/routing/v2/waypoint.proto

require 'google/protobuf'

require 'google/maps/routing/v2/location_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/maps/routing/v2/waypoint.proto", :syntax => :proto3) do
    add_message "google.maps.routing.v2.Waypoint" do
      optional :via, :bool, 3
      optional :vehicle_stopover, :bool, 4
      optional :side_of_road, :bool, 5
      oneof :location_type do
        optional :location, :message, 1, "google.maps.routing.v2.Location"
        optional :place_id, :string, 2
        optional :address, :string, 7
      end
    end
  end
end

module Google
  module Maps
    module Routing
      module V2
        Waypoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.maps.routing.v2.Waypoint").msgclass
      end
    end
  end
end
